### ISSUE TITLE
Deprecate `isOpen`

### ISSUE THREAD

**Issue by srph** [rackt/react-modal#25]
I find this more convenient compared to the current approach.

```js
{ condition ? (
<Modal
  onRequestClose={fn}
  closeTimeoutMS={n}
>
  <h1>Modal Content</h1>
  <p>Etc.</p>
</Modal>
) : null }
```

However, I haven't tried this (whether is works), and I do not acknowledge any pros and cons of the approach besides a cleaner API.

**Comment by cameronsutter** [comment]
I've also found it to be more convenient this way

**Comment by pstoica** [comment]
I think you'd lose out on being able to animate? I don't think you can wrap `<Modal>` in something like `ReactTransitionGroup` since it needs to open up through another portal.

**Comment by srph** [comment]
@pstoica Yea. I just realized this. Closing this because I just made myself look stupid :tada: haha

**Comment by yvele** [comment]
@pstoica @srph @monsieurnebo So basically the whole point of `isOpen` is to allow animations through `ReactTransitionGroup` ?

If I don't have animation, can you confirm that no using `isOpen` and returning `null` (no render atl all) is straightforward and well.. better.

What the point of the portal? Only animation? https://github.com/reactjs/react-modal/pull/205

**Comment by diasbruno** [comment]
The `Modal.js` is responsible for setting all the environment (specially a11y, toggle the body class...). It also contains the timer for the animation since it doesn't uses css events to control its state.

@yvele Can you elaborate your idea to handle this?

Resources:
[Modal.js#L81](https://github.com/reactjs/react-modal/blob/v1/lib/components/Modal.js#L81)
[Modal.js#L110](https://github.com/reactjs/react-modal/blob/v1/lib/components/Modal.js#L110)
[Modal.js#L117](https://github.com/reactjs/react-modal/blob/v1/lib/components/Modal.js#L117)

**Comment by neptunian** [comment]
@yvele @diasbruno  i modified the library a bit and not using isOpen works fine but then you lose out on animation.  The reason I did it is because if i use isOpen i can't get react-router to work properly where i render a component based on a route.  In my app the modals have urls and it seems this modal is designed to be mounted when the page loads and show or hides its children based on the isOpen prop instead of mounting and unmounting the whole component.  I think it'd be better to get rid of the isOpen prop but i don't know how you'd handle animation then.  I was not able to figure that part out.

**Comment by yvele** [comment]
@monsieurnebo CC

**Comment by neptunian** [comment]
I believe i've been able to get it working without having to remove isOpen with react-router by using the children function:
https://reacttraining.com/react-router/web/api/Route/children-func

That way the component mounts no matter what and the modal can continue using isOpen with animation.
