### ISSUE TITLE
what are the requiriments if any?

### ISSUE THREAD

**Issue by TurBoss** [rackt/react-modal#64]
I'm trying to use React-Modal but I'm stuck with "ReferenceError: Modal is not defined"

So I ask if i need something else like a lib or so

thx

**Comment by mzabriskie** [comment]
Do you have any code that you can share?

**Comment by zjjott** [comment]
var ModalPortal = React.createFactory(require('./ModalPortal')); 
raise:
`Uncaught TypeError: Cannot read property 'createFactory' of undefined`

**Comment by laran** [comment]
I'm getting a similar error.

My main app entry point is here:
https://github.com/laran/warehouse/blob/master/warehouse-application-starter/src/main/resources/static/index.html

These are the two files that fail to load properly:

- https://github.com/laran/warehouse/blob/master/warehouse-application-starter/src/main/resources/static/warehouse/js/components/flash-modal.jsx
- https://github.com/laran/warehouse/blob/master/warehouse-application-starter/src/main/resources/static/warehouse/js/components/login-modal.jsx

And here's the error that I get:

![screen shot 2015-09-21 at 1 28 03 am](https://cloud.githubusercontent.com/assets/8204/9987829/1b68bd90-6000-11e5-88c6-4b64b5101681.png)

**Comment by laran** [comment]
If I add this before the code that loaded my application I get past that error:
```
var React = require(['react']);
```

But then I get a different error on this line:
https://github.com/rackt/react-modal/blob/master/lib/components/ModalPortal.js#L2

... because I'm using JSX, and according to [the docs](https://facebook.github.io/react/docs/top-level-api.html#react.dom) React.DOM should never be used when using JSX.

So, I tried replacing React.DOM.div with React.createElement('div') and that failed with "Uncaught TypeError: React.createElement is not a function".

Ideas?

**Comment by TurBoss** [comment]
sry I didn't have time to post, will do soon thx

**Comment by TurBoss** [comment]
well I notice that requirejs didn't work with django-pipeline :(
maybe i will switch to django-require
so is my fault 

thx

**Comment by francisgwhitesell** [comment]
I am also having this issue. I'm importing react and react-modal without module loading. 
`		import Modal from 'react-modal';
`
and I get:
![image](https://cloud.githubusercontent.com/assets/2829262/18518876/b70985d8-7a6f-11e6-927a-85fa2d8ba7f6.png)
and:
![image](https://cloud.githubusercontent.com/assets/2829262/18518904/d08431de-7a6f-11e6-9684-7909424802f7.png)
similar to @laran .

**Comment by geetotes** [comment]
@francisgwhitesell that probably means that `React` is undefined. Are you loading React before you load react-modal?
